### ISSUE TITLE
BlendModeGrabGUI.cs的编码格式

### ISSUE THREAD

**Issue by limitty** [falseeeeeeeeee/ShaderLibrary#1]
感谢大佬开源学习素材 ⭐

Rider打开工程遇到一个编码格式问题：

ShaderLib_2021\Assets\ShaderLib\Tool_BlendModePS\Editor\BlendModeGrabGUI.cs

这个文件默认是GB2312编码格式，用UTF 8打开会乱码，需要先reload为GB2312，再手动转换为UTF 8。

**Comment by falseeeeeeeeee** [comment]
👍，你是最棒的
